### ISSUE TITLE
Title：assemble.py - hybpiper.assemble - assemble - ERROR - ERROR: No genes with reads, exiting!

### ISSUE THREAD

**Issue by wang-CK2** [mossmatters/HybPiper#108] opened 2023-01-21 18:15 UTC
Hello, prof.
I prepared my target seqs (pep) with orthofinder, and ran hybpiper v2 to assemble and extract nuclear genes from genome skimming data. In the process of running, I encountered a similar problem as that raised by  **XiaoTW123** not long ago, but I did not solve my problem by using the two methods (changing the CPU parameters and using the CDS-target seqs from the same reference genomes), while other samples can run successfully. The following is the running log file, please help me to see where the problem is.

#2023-01-18 23:26:34,946 - assemble.py - hybpiper.assemble - assemble - INFO - [INFO]:    HybPiper was called with these arguments:
2023-01-18 23:26:34,946 - assemble.py - hybpiper.assemble - assemble - INFO -            /home/ck/miniconda3/envs/hybpiper/bin/hybpiper assemble -t_aa
           ../diamond_pep_single_copy.fasta -r 2L-81_raw_1.fq.gz 2L-81_raw_2.fq.gz --cpu
           64 --prefix zl81 --diamond
2023-01-18 23:26:34,946 - assemble.py - hybpiper.assemble - assemble - DEBUG - Namespace(readfiles=['2L-81_raw_1.fq.gz', '2L-81_raw_2.fq.gz'], targetfile_dna=False, targetfile_aa='../diamond_pep_single_copy.fasta', bwa=False, diamond=True, diamond_sensitivity=False, start_from='map_reads', cpu=64, distribute_low_mem=False, evalue=0.0001, max_target_seqs=10, cov_cutoff=8, spades_single_cell=False, kvals=None, thresh=55, paralog_min_length_percentage=0.75, depth_multiplier=10, prefix='zl81', timeout_assemble=0, timeout_exonerate_contigs=120, target=None, exclude=None, unpaired=False, no_stitched_contig=False, bbmap_memory=1000, bbmap_subfilter=7, bbmap_threads=1, chimeric_stitched_contig_edit_distance=5, chimeric_stitched_contig_discordant_reads_cutoff=5, merged=False, intronerate=False, keep_intermediate_files=False, no_padding_supercontigs=False, verbose_logging=False, run_profiler=False, blast=True, func=<function assemble at 0x7f93c2ca14e0>)
2023-01-18 23:26:34,946 - assemble.py - hybpiper.assemble - assemble - INFO - [INFO]:    Using 64 cpus/threads.
2023-01-18 23:26:34,946 - assemble.py - hybpiper.assemble - assemble - DEBUG - args.start_from is: map_reads
2023-01-18 23:26:34,946 - utils.py - hybpiper.assemble - log_or_print - INFO - [INFO]:    Checking for external dependencies:

2023-01-18 23:26:34,946 - utils.py - hybpiper.assemble - log_or_print - INFO - blastx               found at /home/ck/miniconda3/envs/hybpiper/bin/blastx
2023-01-18 23:26:34,947 - utils.py - hybpiper.assemble - log_or_print - INFO - exonerate            found at /home/ck/miniconda3/envs/hybpiper/bin/exonerate
2023-01-18 23:26:34,950 - utils.py - hybpiper.assemble - log_or_print - INFO - parallel             found at /home/ck/miniconda3/envs/hybpiper/bin/parallel
2023-01-18 23:26:34,950 - utils.py - hybpiper.assemble - log_or_print - INFO - makeblastdb          found at /home/ck/miniconda3/envs/hybpiper/bin/makeblastdb
2023-01-18 23:26:34,950 - utils.py - hybpiper.assemble - log_or_print - INFO - spades.py            found at /home/ck/miniconda3/envs/hybpiper/bin/spades.py
2023-01-18 23:26:34,950 - utils.py - hybpiper.assemble - log_or_print - INFO - bwa                  found at /home/ck/miniconda3/envs/hybpiper/bin/bwa
2023-01-18 23:26:34,950 - utils.py - hybpiper.assemble - log_or_print - INFO - samtools             found at /home/ck/miniconda3/envs/hybpiper/bin/samtools
2023-01-18 23:26:34,950 - utils.py - hybpiper.assemble - log_or_print - INFO - bbmap.sh             found at /home/ck/miniconda3/envs/hybpiper/bin/bbmap.sh
2023-01-18 23:26:34,951 - utils.py - hybpiper.assemble - log_or_print - INFO - bbmerge.sh           found at /home/ck/miniconda3/envs/hybpiper/bin/bbmerge.sh
2023-01-18 23:26:34,951 - utils.py - hybpiper.assemble - log_or_print - INFO - diamond              found at /home/ck/miniconda3/envs/hybpiper/bin/diamond
2023-01-18 23:26:34,951 - utils.py - hybpiper.assemble - log_or_print - INFO - mafft                found at /home/ck/miniconda3/envs/hybpiper/bin/mafft
2023-01-18 23:26:34,951 - utils.py - hybpiper.assemble - log_or_print - INFO - 
2023-01-18 23:26:34,951 - assemble.py - hybpiper.assemble - assemble - INFO - [INFO]:    Everything looks good!
2023-01-18 23:26:34,951 - assemble.py - hybpiper.assemble - assemble - DEBUG - Input target file diamond_pep_single_copy.fasta exists and is not empty, proceeding...
2023-01-18 23:26:34,951 - assemble.py - hybpiper.assemble - assemble - DEBUG - The target file diamond_pep_single_copy.fasta has been provided, containing protein sequences
2023-01-18 23:26:34,951 - assemble.py - hybpiper.assemble - assemble - DEBUG - Input read file /home/ck/3.hybpiper_assemble_pep/2L-81/2L-81_raw_1.fq.gz exists and is not empty, proceeding...
2023-01-18 23:26:34,951 - assemble.py - hybpiper.assemble - assemble - DEBUG - Input read file /home/ck/3.hybpiper_assemble_pep/2L-81/2L-81_raw_2.fq.gz exists and is not empty, proceeding...
2023-01-18 23:26:34,951 - utils.py - hybpiper.assemble - log_or_print - INFO - [INFO]:    Checking target file FASTA header formatting...
2023-01-18 23:26:34,996 - utils.py - hybpiper.assemble - log_or_print - INFO - [INFO]:    The target file FASTA header formatting looks good!
2023-01-18 23:26:34,996 - utils.py - hybpiper.assemble - log_or_print - INFO - [INFO]:    The target file contains at least one sequence for 1298 unique genes.
2023-01-18 23:26:34,998 - assemble.py - hybpiper.assemble - blastx - INFO - [INFO]:    Making protein blastdb in current directory.
2023-01-18 23:26:34,999 - assemble.py - hybpiper.assemble - blastx - INFO - [INFO]:    Using DIAMOND instead of BLASTx!
2023-01-18 23:26:35,000 - assemble.py - hybpiper.assemble - blastx - INFO - [CMD]:     diamond makedb --in diamond_pep_single_copy.fasta --db
           diamond_pep_single_copy.fasta
2023-01-18 23:26:35,069 - assemble.py - hybpiper.assemble - blastx - DEBUG - makeblastdb check_returncode() is: None
2023-01-18 23:26:35,069 - assemble.py - hybpiper.assemble - blastx - DEBUG - makeblastdb stdout is: 
2023-01-18 23:26:35,069 - assemble.py - hybpiper.assemble - blastx - DEBUG - makeblastdb stderr is: diamond v2.0.15.153 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 112
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: diamond_pep_single_copy.fasta
Opening the database file...  [0s]
Loading sequences...  [0.015s]
Masking sequences...  [0.033s]
Writing sequences...  [0.002s]
Hashing sequences...  [0.001s]
Loading sequences...  [0s]
Writing trailer...  [0s]
Closing the input file...  [0s]
Closing the database file...  [0.001s]

Database sequences  6490
  Database letters  3011392
     Database hash  5a955e593169014657aff12171a21ed6
        Total time  0.055000s

2023-01-18 23:26:35,070 - assemble.py - hybpiper.assemble - blastx - INFO - [CMD]:     diamond blastx --threads 64 --db diamond_pep_single_copy.fasta --query /home/
           ck/3.hybpiper_assemble_pep/
           2L-81/2L-81_raw_1.fq.gz --evalue 0.0001 --outfmt 6 --max-target-seqs 10 >>
           zl81.blastx
2023-01-18 23:32:19,647 - assemble.py - hybpiper.assemble - blastx - DEBUG - blastx paired check_returncode() is: None
2023-01-18 23:32:19,647 - assemble.py - hybpiper.assemble - blastx - DEBUG - blastx paired stdout is: 
2023-01-18 23:32:19,647 - assemble.py - hybpiper.assemble - blastx - DEBUG - blastx paired stderr is: 
2023-01-18 23:32:19,647 - assemble.py - hybpiper.assemble - blastx - INFO - [CMD]:     diamond blastx --threads 64 --db diamond_pep_single_copy.fasta --query /home/
           ck/3.hybpiper_assemble_pep/
           2L-81/2L-81_raw_2.fq.gz --evalue 0.0001 --outfmt 6 --max-target-seqs 10 >>
           zl81.blastx
2023-01-18 23:39:56,758 - assemble.py - hybpiper.assemble - blastx - DEBUG - blastx paired check_returncode() is: None
2023-01-18 23:39:56,758 - assemble.py - hybpiper.assemble - blastx - DEBUG - blastx paired stdout is: 
2023-01-18 23:39:56,758 - assemble.py - hybpiper.assemble - blastx - DEBUG - blastx paired stderr is: 
2023-01-18 23:39:56,758 - distribute_reads_to_targets.py - hybpiper.assemble.hybpiper.distribute_reads_to_targets - read_sorting_blastx - INFO - [INFO]:    Gathering IDs for mapped reads...
2023-01-18 23:39:58,708 - assemble.py - hybpiper.assemble - distribute_blastx - INFO - [INFO]:    In total, 525420 reads from the paired-end read files will be distributed to gene directories
2023-01-18 23:39:58,708 - distribute_reads_to_targets.py - hybpiper.assemble.hybpiper.distribute_reads_to_targets - distribute_reads - DEBUG - Distributing reads from gzipped file 2L-81_raw_1.fq.gz
2023-01-18 23:41:51,989 - distribute_reads_to_targets.py - hybpiper.assemble.hybpiper.distribute_reads_to_targets - distribute_reads - INFO - [NOTE]:    Distributing paired reads to gene directories
2023-01-18 23:41:51,990 - distribute_reads_to_targets.py - hybpiper.assemble.hybpiper.distribute_reads_to_targets - distribute_reads - DEBUG - [NOTE]:    Distributing reads from gzipped file 2L-81_raw_2.fq.gz
2023-01-18 23:46:05,098 - distribute_targets.py - hybpiper.assemble.hybpiper.distribute_targets - distribute_targets - INFO - [NOTE]:    0 genes had no good matches.
2023-01-18 23:46:05,120 - assemble.py - hybpiper.assemble - assemble - ERROR - ERROR: No genes with reads, exiting!

**Comment by chrisjackson-pellicle** [comment] 2023-01-22 22:34
Hi @wang-CK2,

When you say "while other samples can run successfully", do you mean that you've run HybPiper successfully using the same target file, but read files from a different taxon?

Regardless, I suspect that this might be due to the fasta headers in your read files for sample `zl81`. Can you upload a small sample of your read files? You could use commands such as `gunzip -c 2L-81_raw_1.fq.gz | head -n 10000 | gzip > 2L-81_raw_1_sample.fq.gz` and  `gunzip -c 2L-81_raw_2.fq.gz | head -n 10000 | gzip > 2L-81_raw_2_sample.fq.gz` to get the samples.

Cheers,

Chris

**Comment by wang-CK2** [comment] 2023-01-27 12:59
Hi @chrisjackson-pellicle , I'm sorry to reply to you so late.

Yes, i successfully using the same target file, but read files from a different taxon.

" When you say "while other samples can run successfully", do you mean that you've run HybPiper successfully using the same target file, but read files from a different taxon?"
 
I uploaded my file, please check.

" Regardless, I suspect that this might be due to the fasta headers in your read files for sample `zl81`. Can you upload a small sample of your read files? You could use commands such as `gunzip -c 2L-81_raw_1.fq.gz | head -n 10000 | gzip > 2L-81_raw_1_sample.fq.gz` and `gunzip -c 2L-81_raw_2.fq.gz | head -n 10000 | gzip > 2L-81_raw_2_sample.fq.gz` to get the samples."

Thank you very much.
Wang CK
[2L-81_raw_1_sample.fq.gz](https://github.com/mossmatters/HybPiper/files/10519084/2L-81_raw_1_sample.fq.gz)
[2L-81_raw_2_sample.fq.gz](https://github.com/mossmatters/HybPiper/files/10519087/2L-81_raw_2_sample.fq.gz)
[target.txt](https://github.com/mossmatters/HybPiper/files/10519090/target.txt)

**Comment by chrisjackson-pellicle** [comment] 2023-01-31 05:14
Hi @wang-CK2,

Yes, I think your problem was caused by a bug in HybPiper - the older style fasta headers in your read files for this sample (i.e., with suffixes `/1` and `/2` for forward and reverse reads, respectively) weren't being processed correctly when using BLASTx for read mapping.  

I've just pushed HybPiper version 2.1.2 (conda packages have also been updated) which contains a fix for this (see the [changelog](https://github.com/mossmatters/HybPiper/blob/master/change_log.md)). Can you update to HybPiper version 2.1.2 and let me know how you go?

Cheers,

Chris

**Comment by wang-CK2** [comment] 2023-02-05 04:28
Hi@chrisjackson-pellicle,

 Thank you for your help, updating to the latest version 2.1.2 was working in solving my problem, thank you again for your quick reply and help in solving my problem，the target gene sets in both cds and pep formats work successfully and no problems have been found so far. If there are any problems, I will give you feedback as soon as possible, thank you very much!

“I've just pushed HybPiper version 2.1.2 (conda packages have also been updated) which contains a fix for this (see the [changelog](https://github.com/mossmatters/HybPiper/blob/master/change_log.md)). Can you update to HybPiper version 2.1.2 and let me know how you go?”

**Comment by wang-CK2** [comment] 2023-02-05 04:30
Hi@chrisjackson-pellicle,

Thank you for your help, updating to the latest version 2.1.2 was working in solving my problem, thank you again for your quick reply and help in solving my problem，the target gene sets in both cds and pep formats work successfully and no problems have been found so far. If there are any problems, I will give you feedback as soon as possible, thank you very much!

“I've just pushed HybPiper version 2.1.2 (conda packages have also been updated) which contains a fix for this (see the [changelog](https://github.com/mossmatters/HybPiper/blob/master/change_log.md)). Can you update to HybPiper version 2.1.2 and let me know how you go?”
cheers,
Wang CK

**Comment by wang-CK2** [comment] 2023-02-05 04:32
Hi@chrisjackson-pellicle,

Thank you for your help, updating to the latest version 2.1.2 was working in solving my problem, thank you again for your quick reply and help in solving my problem，the target gene sets in both cds and pep formats work successfully and no problems have been found so far. If there are any problems, I will give you feedback as soon as possible, thank you very much!

“I've just pushed HybPiper version 2.1.2 (conda packages have also been updated) which contains a fix for this (see the [changelog](https://github.com/mossmatters/HybPiper/blob/master/change_log.md)). Can you update to HybPiper version 2.1.2 and let me know how you go?”
Cheers,
Wang CK

**Comment by chrisjackson-pellicle** [comment] 2023-02-06 00:59
Great, thanks for letting me know!

**Closed by chrisjackson-pellicle** 2023-02-06 00:59 UTC
